sonar.projectKey=PIA
sonar.working.directory=C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1

AEE5BF25-16AC-4A49-9C66-E394EE432AB7.sonar.projectKey=PIA:AEE5BF25-16AC-4A49-9C66-E394EE432AB7
AEE5BF25-16AC-4A49-9C66-E394EE432AB7.sonar.projectName=XamarinApp1
AEE5BF25-16AC-4A49-9C66-E394EE432AB7.sonar.projectBaseDir=C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1
AEE5BF25-16AC-4A49-9C66-E394EE432AB7.sonar.sourceEncoding=utf-8
AEE5BF25-16AC-4A49-9C66-E394EE432AB7.sonar.sources=\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1\\App.xaml.cs",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1\\AssemblyInfo.cs",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1\\HelperClasses\\LogFile.cs",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1\\MainPage.xaml.cs",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1\\App.xaml",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1\\MainPage.xaml"

AEE5BF25-16AC-4A49-9C66-E394EE432AB7.sonar.cs.roslyn.reportFilePath=C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1\\bin\\Debug\\netstandard2.0\\XamarinApp1.dll.RoslynCA.json
AEE5BF25-16AC-4A49-9C66-E394EE432AB7.sonar.cs.analyzer.projectOutPath=C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\.sonarqube\\out\\0
AEE5BF25-16AC-4A49-9C66-E394EE432AB7.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\.sonarqube\\out\\0"
AEE5BF25-16AC-4A49-9C66-E394EE432AB7.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1\\bin\\Debug\\netstandard2.0\\XamarinApp1.dll.RoslynCA.json"

AEE5BF25-16AC-4A49-9C66-E394EE432AB7.sonar.working.directory=C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\.sonarqube\\out\\.sonar\\mod0
5716C5D2-6551-4EB6-BCC4-8B9B9ED96DD2.sonar.projectKey=PIA:5716C5D2-6551-4EB6-BCC4-8B9B9ED96DD2
5716C5D2-6551-4EB6-BCC4-8B9B9ED96DD2.sonar.projectName=XamarinApp1.Android
5716C5D2-6551-4EB6-BCC4-8B9B9ED96DD2.sonar.projectBaseDir=C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android
5716C5D2-6551-4EB6-BCC4-8B9B9ED96DD2.sonar.sourceEncoding=utf-8
5716C5D2-6551-4EB6-BCC4-8B9B9ED96DD2.sonar.sources=\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Resources\\layout\\Tabbar.xml",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Resources\\layout\\Toolbar.xml",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Resources\\values\\styles.xml",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Resources\\values\\colors.xml",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Resources\\mipmap-anydpi-v26\\icon.xml",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Resources\\mipmap-anydpi-v26\\icon_round.xml",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Resources\\mipmap-hdpi\\icon.png",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Resources\\mipmap-hdpi\\launcher_foreground.png",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Resources\\mipmap-mdpi\\icon.png",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Resources\\mipmap-mdpi\\launcher_foreground.png",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Resources\\mipmap-xhdpi\\icon.png",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Resources\\mipmap-xhdpi\\launcher_foreground.png",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Resources\\mipmap-xxhdpi\\icon.png",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Resources\\mipmap-xxhdpi\\launcher_foreground.png",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Resources\\mipmap-xxxhdpi\\icon.png",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Resources\\mipmap-xxxhdpi\\launcher_foreground.png",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Resources\\xml\\file_paths.xml",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\MainActivity.cs",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Resources\\Resource.designer.cs",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Properties\\AssemblyInfo.cs",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Resources\\AboutResources.txt",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Assets\\AboutAssets.txt",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\Properties\\AndroidManifest.xml"

5716C5D2-6551-4EB6-BCC4-8B9B9ED96DD2.sonar.cs.roslyn.reportFilePath=C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\bin\\Debug\\XamarinApp1.Android.dll.RoslynCA.json
5716C5D2-6551-4EB6-BCC4-8B9B9ED96DD2.sonar.cs.analyzer.projectOutPath=C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\.sonarqube\\out\\1
5716C5D2-6551-4EB6-BCC4-8B9B9ED96DD2.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\.sonarqube\\out\\1"
5716C5D2-6551-4EB6-BCC4-8B9B9ED96DD2.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.Android\\bin\\Debug\\XamarinApp1.Android.dll.RoslynCA.json"

5716C5D2-6551-4EB6-BCC4-8B9B9ED96DD2.sonar.working.directory=C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\.sonarqube\\out\\.sonar\\mod1
11F192E1-6914-4CCC-90B4-10D40D484C4A.sonar.projectKey=PIA:11F192E1-6914-4CCC-90B4-10D40D484C4A
11F192E1-6914-4CCC-90B4-10D40D484C4A.sonar.projectName=XamarinApp1.iOS
11F192E1-6914-4CCC-90B4-10D40D484C4A.sonar.projectBaseDir=C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.iOS
11F192E1-6914-4CCC-90B4-10D40D484C4A.sonar.sourceEncoding=utf-8
11F192E1-6914-4CCC-90B4-10D40D484C4A.sonar.sources=\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.iOS\\Main.cs",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.iOS\\AppDelegate.cs",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.iOS\\Properties\\AssemblyInfo.cs",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.iOS\\Entitlements.plist",\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.iOS\\Info.plist"

11F192E1-6914-4CCC-90B4-10D40D484C4A.sonar.cs.roslyn.reportFilePath=C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.iOS\\bin\\iPhone\\Debug\\XamarinApp1.iOS.exe.RoslynCA.json
11F192E1-6914-4CCC-90B4-10D40D484C4A.sonar.cs.analyzer.projectOutPath=C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\.sonarqube\\out\\2
11F192E1-6914-4CCC-90B4-10D40D484C4A.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\.sonarqube\\out\\2"
11F192E1-6914-4CCC-90B4-10D40D484C4A.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\XamarinApp1\\XamarinApp1.iOS\\bin\\iPhone\\Debug\\XamarinApp1.iOS.exe.RoslynCA.json"

11F192E1-6914-4CCC-90B4-10D40D484C4A.sonar.working.directory=C:\\Users\\harikrishnan.a\\source\\repos\\XamarinApp1\\.sonarqube\\out\\.sonar\\mod2
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=AEE5BF25-16AC-4A49-9C66-E394EE432AB7,5716C5D2-6551-4EB6-BCC4-8B9B9ED96DD2,11F192E1-6914-4CCC-90B4-10D40D484C4A

